/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicDebugPdfRouteImport } from './routes/api/public/debug-pdf'
import { Route as ApiPublicRefreshMenusRouteImport } from './routes/api/public/refresh-menus'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDebugPdfRoute = ApiPublicDebugPdfRouteImport.update({
  id: '/api/public/debug-pdf',
  path: '/api/public/debug-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRefreshMenusRoute = ApiPublicRefreshMenusRouteImport.update({
  id: '/api/public/refresh-menus',
  path: '/api/public/refresh-menus',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/debug-pdf': typeof ApiPublicDebugPdfRoute
  '/api/public/refresh-menus': typeof ApiPublicRefreshMenusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/debug-pdf': typeof ApiPublicDebugPdfRoute
  '/api/public/refresh-menus': typeof ApiPublicRefreshMenusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/debug-pdf': typeof ApiPublicDebugPdfRoute
  '/api/public/refresh-menus': typeof ApiPublicRefreshMenusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/debug-pdf' | '/api/public/refresh-menus'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/debug-pdf' | '/api/public/refresh-menus'
  id: '__root__' | '/' | '/api/public/debug-pdf' | '/api/public/refresh-menus'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicDebugPdfRoute: typeof ApiPublicDebugPdfRoute
  ApiPublicRefreshMenusRoute: typeof ApiPublicRefreshMenusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/debug-pdf': {
      id: '/api/public/debug-pdf'
      path: '/api/public/debug-pdf'
      fullPath: '/api/public/debug-pdf'
      preLoaderRoute: typeof ApiPublicDebugPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/refresh-menus': {
      id: '/api/public/refresh-menus'
      path: '/api/public/refresh-menus'
      fullPath: '/api/public/refresh-menus'
      preLoaderRoute: typeof ApiPublicRefreshMenusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicDebugPdfRoute: ApiPublicDebugPdfRoute,
  ApiPublicRefreshMenusRoute: ApiPublicRefreshMenusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
